load("//bazel:rust_deps.bzl", "aliases", "all_crate_deps", "crate_edition")
load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "sources",
    srcs = glob(["*.rs"]) + [
        "//src/qualitygate/adapters/reports:sources",
        "//src/qualitygate/adapters/syntax:sources",
    ],
)

rust_library(
    name = "adapters",
    crate_name = "qualitygate_adapters",
    crate_root = "bazel_lib.rs",
    srcs = [":sources"],
    aliases = aliases(),
    edition = crate_edition(),
    deps = [
        "//src/qualitygate/config",
        "//src/qualitygate/domain",
        "//src/qualitygate/paths",
        "//src/qualitygate/snapshot",
    ] + all_crate_deps(normal = True),
    proc_macro_deps = all_crate_deps(proc_macro = True),
)

rust_test(
    name = "unit_tests",
    crate = ":adapters",
    aliases = aliases(
        normal_dev = True,
        proc_macro_dev = True,
    ),
    edition = crate_edition(),
    deps = all_crate_deps(normal_dev = True),
    proc_macro_deps = all_crate_deps(proc_macro_dev = True),
)
