//! Persist and normalize only outputs freshly generated by a successful command.

use crate::{config::CommandCheck, domain::CheckResult, snapshot::Snapshot};
use anyhow::Result;
use std::{path::Path, sync::Arc};

pub(super) async fn collect(
    check: &CommandCheck,
    workspace: &Path,
    artifacts: &Path,
    snapshot: &Arc<Snapshot>,
    result: &mut CheckResult,
) -> Result<()> {
    let mut facts = Vec::new();
    for (index, project) in check.projects.iter().enumerate() {
        let model =
            super::generated_reports::read_report(workspace, &project.effective_pom).await?;
        result.execution.artifacts.push(
            super::evidence::persist(
                artifacts,
                &check.id,
                &format!("project-{index}-model"),
                &model,
            )
            .await?,
        );
        let tree =
            super::generated_reports::read_report(workspace, &project.dependency_tree).await?;
        result.execution.artifacts.push(
            super::evidence::persist(
                artifacts,
                &check.id,
                &format!("project-{index}-tree"),
                &tree,
            )
            .await?,
        );
        let spec = project.clone();
        let workspace = workspace.to_owned();
        let snapshot = Arc::clone(snapshot);
        let id = check.id.clone();
        facts.push(
            tokio::task::spawn_blocking(move || {
                crate::adapters::maven::parse(&spec, &model, &tree, &workspace, &snapshot, &id)
            })
            .await??,
        );
    }
    if !facts.is_empty() {
        result
            .metadata
            .insert("projects".into(), serde_json::to_value(facts)?);
    }
    Ok(())
}
